version: '3'

services:
  exporter:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./urls.json:/config/urls.json
    environment:
      - URLS_FILE=/config/urls.json

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"